// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: errors.proto

package errors

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error int32

const (
	Error_NO_ERROR                                       Error = 0
	Error_INTERNAL_SERVER_ERROR                          Error = 199
	Error_IAM_USER_NOT_FOUND                             Error = 200
	Error_IAM_USER_NOT_AUTHORIZED                        Error = 201
	Error_IAM_API_KEY_ALREADY_EXISTS                     Error = 202
	Error_WORKSPACE_NOT_FOUND                            Error = 300
	Error_WORKSPACE_USER_ALREADY_EXISTS                  Error = 302
	Error_WORKSPACE_USER_NOT_FOUND                       Error = 303
	Error_WORKSPACE_USER_ALREADY_ACTIVE                  Error = 304
	Error_WORKSPACE_USER_ALREADY_HAVE_PERSONAL_WORKSPACE Error = 305
	Error_WORKSPACE_PLUGIN_NOT_FOUND                     Error = 306
	Error_WORKSPACE_INVITE_INVALID                       Error = 307
	Error_WORKSPACE_CANNOT_INVITE_TO_PERSONAL_WORKSPACE  Error = 308
	Error_CREDITS_USER_HAS_NO_PARENT                     Error = 400
	Error_CREDITS_OUT_OF_CREDITS                         Error = 401
	Error_CREDITS_USER_ALREADY_HAS_PARENT                Error = 402
	// Ontology errors 500 - 599
	Error_ONTOLOGY_NOT_FOUND Error = 500
	// Chat errors - 600 - 699
	Error_CHAT_NOT_FOUND                         Error = 600
	Error_CHAT_NOT_AUTHORIZED                    Error = 601
	Error_CHAT_COMPLETION_ADAPTOR_DOES_NOT_EXIST Error = 602
	Error_CHAT_CONTEXT_LENGTH_EXCEEDED           Error = 603
	Error_CHAT_MESSAGE_ALREADY_EXISTS            Error = 604
	Error_CHAT_MESSAGE_NOT_FOUND                 Error = 605
	Error_CHAT_INTERNAL_SERVER_ERROR             Error = 699
	// AIModel errors - 700 - 799
	Error_AIMODEL_NOT_FOUND Error = 700
	// Assets errors - 800 - 899
	Error_ASSET_NOT_FOUND      Error = 800
	Error_ASSET_ALREADY_EXISTS Error = 801
	Error_ASSET_REQUEST_ERROR  Error = 802
)

// Enum value maps for Error.
var (
	Error_name = map[int32]string{
		0:   "NO_ERROR",
		199: "INTERNAL_SERVER_ERROR",
		200: "IAM_USER_NOT_FOUND",
		201: "IAM_USER_NOT_AUTHORIZED",
		202: "IAM_API_KEY_ALREADY_EXISTS",
		300: "WORKSPACE_NOT_FOUND",
		302: "WORKSPACE_USER_ALREADY_EXISTS",
		303: "WORKSPACE_USER_NOT_FOUND",
		304: "WORKSPACE_USER_ALREADY_ACTIVE",
		305: "WORKSPACE_USER_ALREADY_HAVE_PERSONAL_WORKSPACE",
		306: "WORKSPACE_PLUGIN_NOT_FOUND",
		307: "WORKSPACE_INVITE_INVALID",
		308: "WORKSPACE_CANNOT_INVITE_TO_PERSONAL_WORKSPACE",
		400: "CREDITS_USER_HAS_NO_PARENT",
		401: "CREDITS_OUT_OF_CREDITS",
		402: "CREDITS_USER_ALREADY_HAS_PARENT",
		500: "ONTOLOGY_NOT_FOUND",
		600: "CHAT_NOT_FOUND",
		601: "CHAT_NOT_AUTHORIZED",
		602: "CHAT_COMPLETION_ADAPTOR_DOES_NOT_EXIST",
		603: "CHAT_CONTEXT_LENGTH_EXCEEDED",
		604: "CHAT_MESSAGE_ALREADY_EXISTS",
		605: "CHAT_MESSAGE_NOT_FOUND",
		699: "CHAT_INTERNAL_SERVER_ERROR",
		700: "AIMODEL_NOT_FOUND",
		800: "ASSET_NOT_FOUND",
		801: "ASSET_ALREADY_EXISTS",
		802: "ASSET_REQUEST_ERROR",
	}
	Error_value = map[string]int32{
		"NO_ERROR":                                       0,
		"INTERNAL_SERVER_ERROR":                          199,
		"IAM_USER_NOT_FOUND":                             200,
		"IAM_USER_NOT_AUTHORIZED":                        201,
		"IAM_API_KEY_ALREADY_EXISTS":                     202,
		"WORKSPACE_NOT_FOUND":                            300,
		"WORKSPACE_USER_ALREADY_EXISTS":                  302,
		"WORKSPACE_USER_NOT_FOUND":                       303,
		"WORKSPACE_USER_ALREADY_ACTIVE":                  304,
		"WORKSPACE_USER_ALREADY_HAVE_PERSONAL_WORKSPACE": 305,
		"WORKSPACE_PLUGIN_NOT_FOUND":                     306,
		"WORKSPACE_INVITE_INVALID":                       307,
		"WORKSPACE_CANNOT_INVITE_TO_PERSONAL_WORKSPACE":  308,
		"CREDITS_USER_HAS_NO_PARENT":                     400,
		"CREDITS_OUT_OF_CREDITS":                         401,
		"CREDITS_USER_ALREADY_HAS_PARENT":                402,
		"ONTOLOGY_NOT_FOUND":                             500,
		"CHAT_NOT_FOUND":                                 600,
		"CHAT_NOT_AUTHORIZED":                            601,
		"CHAT_COMPLETION_ADAPTOR_DOES_NOT_EXIST":         602,
		"CHAT_CONTEXT_LENGTH_EXCEEDED":                   603,
		"CHAT_MESSAGE_ALREADY_EXISTS":                    604,
		"CHAT_MESSAGE_NOT_FOUND":                         605,
		"CHAT_INTERNAL_SERVER_ERROR":                     699,
		"AIMODEL_NOT_FOUND":                              700,
		"ASSET_NOT_FOUND":                                800,
		"ASSET_ALREADY_EXISTS":                           801,
		"ASSET_REQUEST_ERROR":                            802,
	}
)

func (x Error) Enum() *Error {
	p := new(Error)
	*p = x
	return p
}

func (x Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Error) Descriptor() protoreflect.EnumDescriptor {
	return file_errors_proto_enumTypes[0].Descriptor()
}

func (Error) Type() protoreflect.EnumType {
	return &file_errors_proto_enumTypes[0]
}

func (x Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Error.Descriptor instead.
func (Error) EnumDescriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{0}
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          *Error                 `protobuf:"varint,1,opt,name=code,proto3,enum=errors.Error,oneof" json:"code,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	Context       *string                `protobuf:"bytes,3,opt,name=context,proto3,oneof" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorResponse) GetCode() Error {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return Error_NO_ERROR
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *ErrorResponse) GetContext() string {
	if x != nil && x.Context != nil {
		return *x.Context
	}
	return ""
}

var File_errors_proto protoreflect.FileDescriptor

const file_errors_proto_rawDesc = "" +
	"\n" +
	"\ferrors.proto\x12\x06errors\x1a\x0evalidate.proto\x1a\x19google/protobuf/any.proto\"\x96\x01\n" +
	"\rErrorResponse\x12&\n" +
	"\x04code\x18\x01 \x01(\x0e2\r.errors.ErrorH\x00R\x04code\x88\x01\x01\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x01R\amessage\x88\x01\x01\x12\x1d\n" +
	"\acontext\x18\x03 \x01(\tH\x02R\acontext\x88\x01\x01B\a\n" +
	"\x05_codeB\n" +
	"\n" +
	"\b_messageB\n" +
	"\n" +
	"\b_context*\xf2\x06\n" +
	"\x05Error\x12\f\n" +
	"\bNO_ERROR\x10\x00\x12\x1a\n" +
	"\x15INTERNAL_SERVER_ERROR\x10\xc7\x01\x12\x17\n" +
	"\x12IAM_USER_NOT_FOUND\x10\xc8\x01\x12\x1c\n" +
	"\x17IAM_USER_NOT_AUTHORIZED\x10\xc9\x01\x12\x1f\n" +
	"\x1aIAM_API_KEY_ALREADY_EXISTS\x10\xca\x01\x12\x18\n" +
	"\x13WORKSPACE_NOT_FOUND\x10\xac\x02\x12\"\n" +
	"\x1dWORKSPACE_USER_ALREADY_EXISTS\x10\xae\x02\x12\x1d\n" +
	"\x18WORKSPACE_USER_NOT_FOUND\x10\xaf\x02\x12\"\n" +
	"\x1dWORKSPACE_USER_ALREADY_ACTIVE\x10\xb0\x02\x123\n" +
	".WORKSPACE_USER_ALREADY_HAVE_PERSONAL_WORKSPACE\x10\xb1\x02\x12\x1f\n" +
	"\x1aWORKSPACE_PLUGIN_NOT_FOUND\x10\xb2\x02\x12\x1d\n" +
	"\x18WORKSPACE_INVITE_INVALID\x10\xb3\x02\x122\n" +
	"-WORKSPACE_CANNOT_INVITE_TO_PERSONAL_WORKSPACE\x10\xb4\x02\x12\x1f\n" +
	"\x1aCREDITS_USER_HAS_NO_PARENT\x10\x90\x03\x12\x1b\n" +
	"\x16CREDITS_OUT_OF_CREDITS\x10\x91\x03\x12$\n" +
	"\x1fCREDITS_USER_ALREADY_HAS_PARENT\x10\x92\x03\x12\x17\n" +
	"\x12ONTOLOGY_NOT_FOUND\x10\xf4\x03\x12\x13\n" +
	"\x0eCHAT_NOT_FOUND\x10\xd8\x04\x12\x18\n" +
	"\x13CHAT_NOT_AUTHORIZED\x10\xd9\x04\x12+\n" +
	"&CHAT_COMPLETION_ADAPTOR_DOES_NOT_EXIST\x10\xda\x04\x12!\n" +
	"\x1cCHAT_CONTEXT_LENGTH_EXCEEDED\x10\xdb\x04\x12 \n" +
	"\x1bCHAT_MESSAGE_ALREADY_EXISTS\x10\xdc\x04\x12\x1b\n" +
	"\x16CHAT_MESSAGE_NOT_FOUND\x10\xdd\x04\x12\x1f\n" +
	"\x1aCHAT_INTERNAL_SERVER_ERROR\x10\xbb\x05\x12\x16\n" +
	"\x11AIMODEL_NOT_FOUND\x10\xbc\x05\x12\x14\n" +
	"\x0fASSET_NOT_FOUND\x10\xa0\x06\x12\x19\n" +
	"\x14ASSET_ALREADY_EXISTS\x10\xa1\x06\x12\x18\n" +
	"\x13ASSET_REQUEST_ERROR\x10\xa2\x06B/Z-github.com/jupyter-naas/naas-models/go/errorsb\x06proto3"

var (
	file_errors_proto_rawDescOnce sync.Once
	file_errors_proto_rawDescData []byte
)

func file_errors_proto_rawDescGZIP() []byte {
	file_errors_proto_rawDescOnce.Do(func() {
		file_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_errors_proto_rawDesc), len(file_errors_proto_rawDesc)))
	})
	return file_errors_proto_rawDescData
}

var file_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_errors_proto_goTypes = []any{
	(Error)(0),            // 0: errors.Error
	(*ErrorResponse)(nil), // 1: errors.ErrorResponse
}
var file_errors_proto_depIdxs = []int32{
	0, // 0: errors.ErrorResponse.code:type_name -> errors.Error
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_errors_proto_init() }
func file_errors_proto_init() {
	if File_errors_proto != nil {
		return
	}
	file_errors_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_errors_proto_rawDesc), len(file_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errors_proto_goTypes,
		DependencyIndexes: file_errors_proto_depIdxs,
		EnumInfos:         file_errors_proto_enumTypes,
		MessageInfos:      file_errors_proto_msgTypes,
	}.Build()
	File_errors_proto = out.File
	file_errors_proto_goTypes = nil
	file_errors_proto_depIdxs = nil
}
