// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.26.1
// source: registry.proto

package registry

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistryError int32

const (
	RegistryError_REGISTRY_ALREADY_EXISTS RegistryError = 0
	RegistryError_REGISTRY_NOT_FOUND      RegistryError = 1
	RegistryError_NOT_AUTHORIZED          RegistryError = 2
)

// Enum value maps for RegistryError.
var (
	RegistryError_name = map[int32]string{
		0: "REGISTRY_ALREADY_EXISTS",
		1: "REGISTRY_NOT_FOUND",
		2: "NOT_AUTHORIZED",
	}
	RegistryError_value = map[string]int32{
		"REGISTRY_ALREADY_EXISTS": 0,
		"REGISTRY_NOT_FOUND":      1,
		"NOT_AUTHORIZED":          2,
	}
)

func (x RegistryError) Enum() *RegistryError {
	p := new(RegistryError)
	*p = x
	return p
}

func (x RegistryError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegistryError) Descriptor() protoreflect.EnumDescriptor {
	return file_registry_proto_enumTypes[0].Descriptor()
}

func (RegistryError) Type() protoreflect.EnumType {
	return &file_registry_proto_enumTypes[0]
}

func (x RegistryError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegistryError.Descriptor instead.
func (RegistryError) EnumDescriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{0}
}

type Registry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	UserId        *string                `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	Uri           *string                `protobuf:"bytes,3,opt,name=uri,proto3,oneof" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registry) Reset() {
	*x = Registry{}
	mi := &file_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registry) ProtoMessage() {}

func (x *Registry) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registry.ProtoReflect.Descriptor instead.
func (*Registry) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{0}
}

func (x *Registry) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Registry) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *Registry) GetUri() string {
	if x != nil && x.Uri != nil {
		return *x.Uri
	}
	return ""
}

type RegistryCredentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      *string                `protobuf:"bytes,2,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Password      *string                `protobuf:"bytes,3,opt,name=password,proto3,oneof" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryCredentials) Reset() {
	*x = RegistryCredentials{}
	mi := &file_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryCredentials) ProtoMessage() {}

func (x *RegistryCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryCredentials.ProtoReflect.Descriptor instead.
func (*RegistryCredentials) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{1}
}

func (x *RegistryCredentials) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *RegistryCredentials) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

type RegistryCreationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryCreationRequest) Reset() {
	*x = RegistryCreationRequest{}
	mi := &file_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryCreationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryCreationRequest) ProtoMessage() {}

func (x *RegistryCreationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryCreationRequest.ProtoReflect.Descriptor instead.
func (*RegistryCreationRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{2}
}

func (x *RegistryCreationRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type RegistryCreationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registry      *Registry              `protobuf:"bytes,1,opt,name=registry,proto3,oneof" json:"registry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryCreationResponse) Reset() {
	*x = RegistryCreationResponse{}
	mi := &file_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryCreationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryCreationResponse) ProtoMessage() {}

func (x *RegistryCreationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryCreationResponse.ProtoReflect.Descriptor instead.
func (*RegistryCreationResponse) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{3}
}

func (x *RegistryCreationResponse) GetRegistry() *Registry {
	if x != nil {
		return x.Registry
	}
	return nil
}

type RegistryCreationResponseError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *RegistryError         `protobuf:"varint,1,opt,name=error,proto3,enum=registry.RegistryError,oneof" json:"error,omitempty"`
	ErrorMessage  *string                `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryCreationResponseError) Reset() {
	*x = RegistryCreationResponseError{}
	mi := &file_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryCreationResponseError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryCreationResponseError) ProtoMessage() {}

func (x *RegistryCreationResponseError) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryCreationResponseError.ProtoReflect.Descriptor instead.
func (*RegistryCreationResponseError) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{4}
}

func (x *RegistryCreationResponseError) GetError() RegistryError {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return RegistryError_REGISTRY_ALREADY_EXISTS
}

func (x *RegistryCreationResponseError) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

type RegistryListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      *int32                 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	PageNumber    *int32                 `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3,oneof" json:"page_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryListRequest) Reset() {
	*x = RegistryListRequest{}
	mi := &file_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryListRequest) ProtoMessage() {}

func (x *RegistryListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryListRequest.ProtoReflect.Descriptor instead.
func (*RegistryListRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{5}
}

func (x *RegistryListRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *RegistryListRequest) GetPageNumber() int32 {
	if x != nil && x.PageNumber != nil {
		return *x.PageNumber
	}
	return 0
}

type RegistryListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registries    []*Registry            `protobuf:"bytes,1,rep,name=registries,proto3" json:"registries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryListResponse) Reset() {
	*x = RegistryListResponse{}
	mi := &file_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryListResponse) ProtoMessage() {}

func (x *RegistryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryListResponse.ProtoReflect.Descriptor instead.
func (*RegistryListResponse) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{6}
}

func (x *RegistryListResponse) GetRegistries() []*Registry {
	if x != nil {
		return x.Registries
	}
	return nil
}

type RegistryGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryGetRequest) Reset() {
	*x = RegistryGetRequest{}
	mi := &file_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryGetRequest) ProtoMessage() {}

func (x *RegistryGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryGetRequest.ProtoReflect.Descriptor instead.
func (*RegistryGetRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{7}
}

func (x *RegistryGetRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type RegistryGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registry      *Registry              `protobuf:"bytes,1,opt,name=registry,proto3,oneof" json:"registry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryGetResponse) Reset() {
	*x = RegistryGetResponse{}
	mi := &file_registry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryGetResponse) ProtoMessage() {}

func (x *RegistryGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryGetResponse.ProtoReflect.Descriptor instead.
func (*RegistryGetResponse) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{8}
}

func (x *RegistryGetResponse) GetRegistry() *Registry {
	if x != nil {
		return x.Registry
	}
	return nil
}

type RegistryGetResponseError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *RegistryError         `protobuf:"varint,1,opt,name=error,proto3,enum=registry.RegistryError,oneof" json:"error,omitempty"`
	ErrorMessage  *string                `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryGetResponseError) Reset() {
	*x = RegistryGetResponseError{}
	mi := &file_registry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryGetResponseError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryGetResponseError) ProtoMessage() {}

func (x *RegistryGetResponseError) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryGetResponseError.ProtoReflect.Descriptor instead.
func (*RegistryGetResponseError) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{9}
}

func (x *RegistryGetResponseError) GetError() RegistryError {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return RegistryError_REGISTRY_ALREADY_EXISTS
}

func (x *RegistryGetResponseError) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

type RegistryDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryDeleteRequest) Reset() {
	*x = RegistryDeleteRequest{}
	mi := &file_registry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryDeleteRequest) ProtoMessage() {}

func (x *RegistryDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryDeleteRequest.ProtoReflect.Descriptor instead.
func (*RegistryDeleteRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{10}
}

func (x *RegistryDeleteRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type RegistryDeleteResponseError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *RegistryError         `protobuf:"varint,1,opt,name=error,proto3,enum=registry.RegistryError,oneof" json:"error,omitempty"`
	ErrorMessage  *string                `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryDeleteResponseError) Reset() {
	*x = RegistryDeleteResponseError{}
	mi := &file_registry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryDeleteResponseError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryDeleteResponseError) ProtoMessage() {}

func (x *RegistryDeleteResponseError) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryDeleteResponseError.ProtoReflect.Descriptor instead.
func (*RegistryDeleteResponseError) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{11}
}

func (x *RegistryDeleteResponseError) GetError() RegistryError {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return RegistryError_REGISTRY_ALREADY_EXISTS
}

func (x *RegistryDeleteResponseError) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

type RegistryCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryCredentialsRequest) Reset() {
	*x = RegistryCredentialsRequest{}
	mi := &file_registry_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryCredentialsRequest) ProtoMessage() {}

func (x *RegistryCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryCredentialsRequest.ProtoReflect.Descriptor instead.
func (*RegistryCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{12}
}

func (x *RegistryCredentialsRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type RegistryCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Credentials   *RegistryCredentials   `protobuf:"bytes,2,opt,name=credentials,proto3,oneof" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryCredentialsResponse) Reset() {
	*x = RegistryCredentialsResponse{}
	mi := &file_registry_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryCredentialsResponse) ProtoMessage() {}

func (x *RegistryCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryCredentialsResponse.ProtoReflect.Descriptor instead.
func (*RegistryCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{13}
}

func (x *RegistryCredentialsResponse) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *RegistryCredentialsResponse) GetCredentials() *RegistryCredentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type RegistryCredentialsResponseError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *RegistryError         `protobuf:"varint,1,opt,name=error,proto3,enum=registry.RegistryError,oneof" json:"error,omitempty"`
	ErrorMessage  *string                `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryCredentialsResponseError) Reset() {
	*x = RegistryCredentialsResponseError{}
	mi := &file_registry_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryCredentialsResponseError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryCredentialsResponseError) ProtoMessage() {}

func (x *RegistryCredentialsResponseError) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryCredentialsResponseError.ProtoReflect.Descriptor instead.
func (*RegistryCredentialsResponseError) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{14}
}

func (x *RegistryCredentialsResponseError) GetError() RegistryError {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return RegistryError_REGISTRY_ALREADY_EXISTS
}

func (x *RegistryCredentialsResponseError) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

var File_registry_proto protoreflect.FileDescriptor

const file_registry_proto_rawDesc = "" +
	"\n" +
	"\x0eregistry.proto\x12\bregistry\x1a\x0evalidate.proto\"\xa2\x01\n" +
	"\bRegistry\x12D\n" +
	"\x04name\x18\x01 \x01(\tB+\xfaB(r&\x10\x01\x18?2 ^([A-Za-z0-9]+(-[A-Za-z0-9]+)+)$H\x00R\x04name\x88\x01\x01\x12\x1c\n" +
	"\auser_id\x18\x02 \x01(\tH\x01R\x06userId\x88\x01\x01\x12\x15\n" +
	"\x03uri\x18\x03 \x01(\tH\x02R\x03uri\x88\x01\x01B\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_user_idB\x06\n" +
	"\x04_uri\"q\n" +
	"\x13RegistryCredentials\x12\x1f\n" +
	"\busername\x18\x02 \x01(\tH\x00R\busername\x88\x01\x01\x12\x1f\n" +
	"\bpassword\x18\x03 \x01(\tH\x01R\bpassword\x88\x01\x01B\v\n" +
	"\t_usernameB\v\n" +
	"\t_password\"h\n" +
	"\x17RegistryCreationRequest\x12D\n" +
	"\x04name\x18\x01 \x01(\tB+\xfaB(r&\x10\x01\x18?2 ^([A-Za-z0-9]+(-[A-Za-z0-9]+)+)$H\x00R\x04name\x88\x01\x01B\a\n" +
	"\x05_name\"\\\n" +
	"\x18RegistryCreationResponse\x123\n" +
	"\bregistry\x18\x01 \x01(\v2\x12.registry.RegistryH\x00R\bregistry\x88\x01\x01B\v\n" +
	"\t_registry\"\x99\x01\n" +
	"\x1dRegistryCreationResponseError\x122\n" +
	"\x05error\x18\x01 \x01(\x0e2\x17.registry.RegistryErrorH\x00R\x05error\x88\x01\x01\x12(\n" +
	"\rerror_message\x18\x02 \x01(\tH\x01R\ferrorMessage\x88\x01\x01B\b\n" +
	"\x06_errorB\x10\n" +
	"\x0e_error_message\"{\n" +
	"\x13RegistryListRequest\x12 \n" +
	"\tpage_size\x18\x01 \x01(\x05H\x00R\bpageSize\x88\x01\x01\x12$\n" +
	"\vpage_number\x18\x02 \x01(\x05H\x01R\n" +
	"pageNumber\x88\x01\x01B\f\n" +
	"\n" +
	"_page_sizeB\x0e\n" +
	"\f_page_number\"J\n" +
	"\x14RegistryListResponse\x122\n" +
	"\n" +
	"registries\x18\x01 \x03(\v2\x12.registry.RegistryR\n" +
	"registries\"c\n" +
	"\x12RegistryGetRequest\x12D\n" +
	"\x04name\x18\x01 \x01(\tB+\xfaB(r&\x10\x01\x18?2 ^([A-Za-z0-9]+(-[A-Za-z0-9]+)+)$H\x00R\x04name\x88\x01\x01B\a\n" +
	"\x05_name\"W\n" +
	"\x13RegistryGetResponse\x123\n" +
	"\bregistry\x18\x01 \x01(\v2\x12.registry.RegistryH\x00R\bregistry\x88\x01\x01B\v\n" +
	"\t_registry\"\x94\x01\n" +
	"\x18RegistryGetResponseError\x122\n" +
	"\x05error\x18\x01 \x01(\x0e2\x17.registry.RegistryErrorH\x00R\x05error\x88\x01\x01\x12(\n" +
	"\rerror_message\x18\x02 \x01(\tH\x01R\ferrorMessage\x88\x01\x01B\b\n" +
	"\x06_errorB\x10\n" +
	"\x0e_error_message\"9\n" +
	"\x15RegistryDeleteRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01B\a\n" +
	"\x05_name\"\x97\x01\n" +
	"\x1bRegistryDeleteResponseError\x122\n" +
	"\x05error\x18\x01 \x01(\x0e2\x17.registry.RegistryErrorH\x00R\x05error\x88\x01\x01\x12(\n" +
	"\rerror_message\x18\x02 \x01(\tH\x01R\ferrorMessage\x88\x01\x01B\b\n" +
	"\x06_errorB\x10\n" +
	"\x0e_error_message\"k\n" +
	"\x1aRegistryCredentialsRequest\x12D\n" +
	"\x04name\x18\x01 \x01(\tB+\xfaB(r&\x10\x01\x18?2 ^([A-Za-z0-9]+(-[A-Za-z0-9]+)+)$H\x00R\x04name\x88\x01\x01B\a\n" +
	"\x05_name\"\xc2\x01\n" +
	"\x1bRegistryCredentialsResponse\x12D\n" +
	"\x04name\x18\x01 \x01(\tB+\xfaB(r&\x10\x01\x18?2 ^([A-Za-z0-9]+(-[A-Za-z0-9]+)+)$H\x00R\x04name\x88\x01\x01\x12D\n" +
	"\vcredentials\x18\x02 \x01(\v2\x1d.registry.RegistryCredentialsH\x01R\vcredentials\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_credentials\"\x9c\x01\n" +
	" RegistryCredentialsResponseError\x122\n" +
	"\x05error\x18\x01 \x01(\x0e2\x17.registry.RegistryErrorH\x00R\x05error\x88\x01\x01\x12(\n" +
	"\rerror_message\x18\x02 \x01(\tH\x01R\ferrorMessage\x88\x01\x01B\b\n" +
	"\x06_errorB\x10\n" +
	"\x0e_error_message*X\n" +
	"\rRegistryError\x12\x1b\n" +
	"\x17REGISTRY_ALREADY_EXISTS\x10\x00\x12\x16\n" +
	"\x12REGISTRY_NOT_FOUND\x10\x01\x12\x12\n" +
	"\x0eNOT_AUTHORIZED\x10\x02B1Z/github.com/jupyter-naas/naas-models/go/registryb\x06proto3"

var (
	file_registry_proto_rawDescOnce sync.Once
	file_registry_proto_rawDescData []byte
)

func file_registry_proto_rawDescGZIP() []byte {
	file_registry_proto_rawDescOnce.Do(func() {
		file_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_registry_proto_rawDesc), len(file_registry_proto_rawDesc)))
	})
	return file_registry_proto_rawDescData
}

var file_registry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_registry_proto_goTypes = []any{
	(RegistryError)(0),                       // 0: registry.RegistryError
	(*Registry)(nil),                         // 1: registry.Registry
	(*RegistryCredentials)(nil),              // 2: registry.RegistryCredentials
	(*RegistryCreationRequest)(nil),          // 3: registry.RegistryCreationRequest
	(*RegistryCreationResponse)(nil),         // 4: registry.RegistryCreationResponse
	(*RegistryCreationResponseError)(nil),    // 5: registry.RegistryCreationResponseError
	(*RegistryListRequest)(nil),              // 6: registry.RegistryListRequest
	(*RegistryListResponse)(nil),             // 7: registry.RegistryListResponse
	(*RegistryGetRequest)(nil),               // 8: registry.RegistryGetRequest
	(*RegistryGetResponse)(nil),              // 9: registry.RegistryGetResponse
	(*RegistryGetResponseError)(nil),         // 10: registry.RegistryGetResponseError
	(*RegistryDeleteRequest)(nil),            // 11: registry.RegistryDeleteRequest
	(*RegistryDeleteResponseError)(nil),      // 12: registry.RegistryDeleteResponseError
	(*RegistryCredentialsRequest)(nil),       // 13: registry.RegistryCredentialsRequest
	(*RegistryCredentialsResponse)(nil),      // 14: registry.RegistryCredentialsResponse
	(*RegistryCredentialsResponseError)(nil), // 15: registry.RegistryCredentialsResponseError
}
var file_registry_proto_depIdxs = []int32{
	1, // 0: registry.RegistryCreationResponse.registry:type_name -> registry.Registry
	0, // 1: registry.RegistryCreationResponseError.error:type_name -> registry.RegistryError
	1, // 2: registry.RegistryListResponse.registries:type_name -> registry.Registry
	1, // 3: registry.RegistryGetResponse.registry:type_name -> registry.Registry
	0, // 4: registry.RegistryGetResponseError.error:type_name -> registry.RegistryError
	0, // 5: registry.RegistryDeleteResponseError.error:type_name -> registry.RegistryError
	2, // 6: registry.RegistryCredentialsResponse.credentials:type_name -> registry.RegistryCredentials
	0, // 7: registry.RegistryCredentialsResponseError.error:type_name -> registry.RegistryError
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_registry_proto_init() }
func file_registry_proto_init() {
	if File_registry_proto != nil {
		return
	}
	file_registry_proto_msgTypes[0].OneofWrappers = []any{}
	file_registry_proto_msgTypes[1].OneofWrappers = []any{}
	file_registry_proto_msgTypes[2].OneofWrappers = []any{}
	file_registry_proto_msgTypes[3].OneofWrappers = []any{}
	file_registry_proto_msgTypes[4].OneofWrappers = []any{}
	file_registry_proto_msgTypes[5].OneofWrappers = []any{}
	file_registry_proto_msgTypes[7].OneofWrappers = []any{}
	file_registry_proto_msgTypes[8].OneofWrappers = []any{}
	file_registry_proto_msgTypes[9].OneofWrappers = []any{}
	file_registry_proto_msgTypes[10].OneofWrappers = []any{}
	file_registry_proto_msgTypes[11].OneofWrappers = []any{}
	file_registry_proto_msgTypes[12].OneofWrappers = []any{}
	file_registry_proto_msgTypes[13].OneofWrappers = []any{}
	file_registry_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_registry_proto_rawDesc), len(file_registry_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_registry_proto_goTypes,
		DependencyIndexes: file_registry_proto_depIdxs,
		EnumInfos:         file_registry_proto_enumTypes,
		MessageInfos:      file_registry_proto_msgTypes,
	}.Build()
	File_registry_proto = out.File
	file_registry_proto_goTypes = nil
	file_registry_proto_depIdxs = nil
}
